name: ut

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  docker:
    name: ut
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Enable ipv4 and ipv6 forwarding
        run: |
          sudo sysctl -w net.ipv6.conf.all.forwarding=1
          sudo sysctl -w net.ipv4.ip_forward=1

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Install kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Install kind
        run: | 
          wget https://github.com/kubernetes-sigs/kind/releases/download/v0.11.0/kind-linux-amd64
          chmod +x kind-linux-amd64
          sudo mv kind-linux-amd64 /usr/bin/kind

      - name: Setup kind cluster
        run: kind create cluster --config=./hack/kind_config.yaml && kind get kubeconfig > /tmp/admin.conf

      - name: Get Cluster status
        run: |
          export KUBECONFIG="/tmp/admin.conf"
          kubectl wait --for=condition=ready pods --namespace=kube-system -l k8s-app=kube-dns
          kubectl get nodes -o wide

      - name: Run go mod
        run: go mod tidy

      - name: Run unit test
        run: go test ./pkg/... -v

      - name: Delete cluster
        run: /usr/local/bin/kind delete cluster
